--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem/SimplePets BUILD.
build-by-default: true
branches:
- master

projects:
  SimplePets:
    icon: "/assets/logo-min.png"
    libs:
      - src: PoggitTestPlugins/libasynql/libasynql
        version: ^3.4.0
        branch: "4.0"
      - src: PoggitTestPlugins/InvMenu/InvMenu
        version: ^4.3.2
        branch: "4.0"
...
